### ISSUE TITLE
is the bootloader different to that for 32bit rpi?

### ISSUE THREAD

**Issue by SvenDowideit** [DieterReuter/workshop-raspberrypi-64bit-os#1]
on the bootloader page, it would be nice to indicate if its exactly the same, or what differences there are :)

**Comment by DieterReuter** [comment]
The bootloader software from the Raspberry Pi repo is exactly the same to use for 32 and 64bit. The hardware will be checked at boot time, so the bootloader knows the correct HW and tries to load the 64bit kernel only on RPi3. If there's no 64bit kernel it falls back to load a 32bit kernel and so on.

For us it's cool, because it just magically works.
